version: 2
updates:
- package-ecosystem: "npm"
directory: "/" 
schedule:
    interval: "weekly"
open-pull-requests-limit: 10
labels:
    - dependencies
    - automerge
commit-message:
    prefix: "deps"
    prefix-development: "dev-deps"
    include: "scope"
reviewers:
    - techthumb1
assignees:
    - techthumb1
ignore:
    - dependency-name: "eslint"
        versions: ["<8.0.0"]
        
    - dependency-name: "typescript"
        versions: ["<5.0.0"]
    
    - package-ecosystem: "github-actions"
directory: "/"
schedule:
    interval: "monthly"
open-pull-requests-limit: 5
labels:
    - dependencies
    - github-actions
reviewers:
    - techthumb1
assignees:
    - techthumb1
ignore:
    - dependency-name: "actions/setup-node"
      versions: ["<3.0.0"]
